apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloworld-api
  name: helloworld-api
spec:
  ports:
  - name: helloworld-api
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: helloworld-api
    tier: backend
status:
  loadBalancer: {}
